apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octopi-ingress
  namespace: {{ octopi_namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: octopi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  octopi-service
                port:
                  number: 80