---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopi
  labels:
    app: octopi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octopi
  template:
    metadata:
      labels:
        app: octopi
    spec:
      containers:
      - name: octopi
        image: octoprint/octoprint
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "300Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: octopi
          mountPath: /octoprint
      nodeName: {{octoprint_node}}
      volumes:
        - name: octopi
          persistentVolumeClaim:
            claimName: octopi-claim

